# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import segmentacao_pb2 as segmentacao__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in segmentacao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SegmentacaoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessarBloco = channel.unary_unary(
                '/segmentacao.SegmentacaoService/ProcessarBloco',
                request_serializer=segmentacao__pb2.BlocoImagemRequest.SerializeToString,
                response_deserializer=segmentacao__pb2.BlocoImagemResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/segmentacao.SegmentacaoService/Status',
                request_serializer=segmentacao__pb2.StatusRequest.SerializeToString,
                response_deserializer=segmentacao__pb2.StatusResponse.FromString,
                _registered_method=True)


class SegmentacaoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessarBloco(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SegmentacaoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessarBloco': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessarBloco,
                    request_deserializer=segmentacao__pb2.BlocoImagemRequest.FromString,
                    response_serializer=segmentacao__pb2.BlocoImagemResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=segmentacao__pb2.StatusRequest.FromString,
                    response_serializer=segmentacao__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'segmentacao.SegmentacaoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('segmentacao.SegmentacaoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SegmentacaoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessarBloco(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/segmentacao.SegmentacaoService/ProcessarBloco',
            segmentacao__pb2.BlocoImagemRequest.SerializeToString,
            segmentacao__pb2.BlocoImagemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/segmentacao.SegmentacaoService/Status',
            segmentacao__pb2.StatusRequest.SerializeToString,
            segmentacao__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
